services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "3000:3000"
        enviroment:
            - NODE_ENV=production
            - DB_HOST=db
            - DB_NAME=dbpetday
            - DB_USER=root
            - DB_PASS=1234
            - JWT_SECRET=SQDSASHU
        depends_on:
            - db
        networks:
            - petday-networks
    
    frontend:
        build:
            context: ./petday-app
            dockerfile: dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - backend
        networks:
            - petday-networks
    
    db:
        image: mysql:8.0
        enviroment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: dbpetday
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - petday-network
volumes:
    db-data:

networks:
    petday-networks:
        driver: bridge